import { useState, useMemo } from "react";
import { useElementContext } from "../context/ElementCreateContext.jsx";
import { useStyleContext } from "../context/StyleContext.jsx";

export default function CodePanel() {
  const { elements } = useElementContext();
  const { styles } = useStyleContext();
  const [activeTab, setActiveTab] = useState("html");

  // --- GENERATORS ---

  // 1. Generate HTML String
  const generateHTML = useMemo(() => {
    const traverse = (nodes, indent = 0) => {
      return nodes
        .map((node) => {
          const spaces = " ".repeat(indent);
          const classAttr =
            node.classList && node.classList.length > 0
              ? ` class="${node.classList.join(" ")}"`
              : "";
          const idAttr = ` id="${node.id}"`;
          
          // Handle specific props like src for images
          const propsAttr = Object.entries(node.props || {})
            .map(([k, v]) => (v ? ` ${k}="${v}"` : ""))
            .join("");

          const openTag = `${spaces}<${node.elementType}${idAttr}${classAttr}${propsAttr}>`;

          let inner = "";
          if (node.content) inner += `\n${" ".repeat(indent + 2)}${node.content}`;
          
          if (node.children && node.children.length > 0) {
            inner += "\n" + traverse(node.children, indent + 2);
          }

          if (inner) inner += `\n${spaces}`;

          // Self-closing tags
          if (['img', 'br', 'hr', 'input'].includes(node.elementType)) {
            return `${spaces}<${node.elementType}${idAttr}${classAttr}${propsAttr} />`;
          }

          return `${openTag}${inner}</${node.elementType}>`;
        })
        .join("\n");
    };

    return `<!-- Generated by LandingBuilder -->\n<div id="root">\n${traverse(elements, 2)}\n</div>`;
  }, [elements]);

  // 2. Generate CSS String
  const generateCSS = useMemo(() => {
    const cssString = Object.entries(styles)
      .map(([id, rules]) => {
        if (Object.keys(rules).length === 0) return "";

        const ruleBlock = Object.entries(rules)
          .map(([prop, value]) => {
            // Convert camelCase to kebab-case (e.g. backgroundColor -> background-color)
            const kebabProp = prop.replace(
              /([a-z0-9])([A-Z])/g,
              "$1-$2"
            ).toLowerCase();

            // Add 'px' to numbers for specific properties if value is a number
            const needsPx =
              typeof value === "number" &&
              [
                "width",
                "height",
                "padding",
                "margin",
                "fontSize",
                "borderRadius",
                "top",
                "left",
                "right",
                "bottom",
                "gap",
                "borderWidth",
              ].some((p) => prop.toLowerCase().includes(p.toLowerCase()));

            return `  ${kebabProp}: ${value}${needsPx ? "px" : ""};`;
          })
          .join("\n");

        return `#${id} {\n${ruleBlock}\n}`;
      })
      .join("\n\n");

    return `/* Global Reset */\n* { box-sizing: border-box; }\nbody { margin: 0; font-family: sans-serif; }\n\n/* Custom Styles */\n${cssString}`;
  }, [styles]);

  // 3. Generate JS String (Boilerplate)
  const generateJS = `
// LandingPage Logic
document.addEventListener('DOMContentLoaded', () => {
  console.log('Landing Page Loaded');
  
  const buttons = document.querySelectorAll('button');
  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      console.log('Button clicked:', btn.id);
    });
  });
});
  `.trim();

  // --- RENDER ---

  let codeToDisplay = "";
  switch (activeTab) {
    case "html":
      codeToDisplay = generateHTML;
      break;
    case "css":
      codeToDisplay = generateCSS;
      break;
    case "js":
      codeToDisplay = generateJS;
      break;
    default:
      codeToDisplay = "";
  }

  return (
    <div className="w-full h-64 border-t bg-[#1e1e1e] text-gray-300 flex flex-col">
      {/* Tabs */}
      <div className="flex items-center bg-[#252526] px-2 border-b border-[#333]">
        <TabButton
          label="HTML"
          active={activeTab === "html"}
          onClick={() => setActiveTab("html")}
        />
        <TabButton
          label="CSS"
          active={activeTab === "css"}
          onClick={() => setActiveTab("css")}
        />
        <TabButton
          label="JavaScript"
          active={activeTab === "js"}
          onClick={() => setActiveTab("js")}
        />
      </div>

      {/* Code Display */}
      <div className="flex-1 overflow-auto p-4 font-mono text-sm">
        <pre>
          <code>{codeToDisplay}</code>
        </pre>
      </div>
    </div>
  );
}

// Helper Component for Tabs
function TabButton({ label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`
        px-4 py-2 text-xs font-medium transition-colors border-r border-[#333]
        ${
          active
            ? "bg-[#1e1e1e] text-white border-t-2 border-t-blue-500"
            : "bg-[#2d2d2d] text-gray-500 hover:bg-[#2a2a2a]"
        }
      `}
    >
      {label}
    </button>
  );
}